// <auto-generated />
using System;
using AuctionManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionManagementAPI.Migrations
{
    [DbContext(typeof(AuctionContext))]
    [Migration("20241029131251_Update Category 3")]
    partial class UpdateCategory3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuctionLable", b =>
                {
                    b.Property<int>("AuctionsAuctionId")
                        .HasColumnType("int");

                    b.Property<int>("LablesLableId")
                        .HasColumnType("int");

                    b.HasKey("AuctionsAuctionId", "LablesLableId");

                    b.HasIndex("LablesLableId");

                    b.ToTable("AuctionLables", (string)null);
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogId"));

                    b.Property<string>("ActivityDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ActivityLogId");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Auction", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionId"));

                    b.Property<bool>("AcceptReturn")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IrregularDimension")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSold")
                        .HasColumnType("bit");

                    b.Property<string>("PackageDimension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PackageWeight")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnAllowedWithin")
                        .HasColumnType("int");

                    b.Property<string>("ReturnMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnShippingPaidBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartingBid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AuctionId");

                    b.HasIndex("ProductId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.AuctionSchedule", b =>
                {
                    b.Property<int>("AuctionScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionScheduleId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("RecurrentPattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AuctionScheduleId");

                    b.HasIndex("AuctionId")
                        .IsUnique();

                    b.ToTable("auctionSchedules");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsWinningBid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BidId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Lable", b =>
                {
                    b.Property<int>("LableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LableId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LableId");

                    b.ToTable("Lables");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Otp", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtpType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OtpId");

                    b.HasIndex("UserId");

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<int>("BidId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("AuctionId")
                        .IsUnique();

                    b.HasIndex("BidId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            Name = "to_create_auction"
                        },
                        new
                        {
                            PermissionId = 2,
                            Name = "to_update_auction"
                        },
                        new
                        {
                            PermissionId = 3,
                            Name = "to_delete_auction"
                        },
                        new
                        {
                            PermissionId = 4,
                            Name = "to_get_all_auctions"
                        },
                        new
                        {
                            PermissionId = 5,
                            Name = "to_get_auction_by_id"
                        },
                        new
                        {
                            PermissionId = 6,
                            Name = "to_create_bid"
                        },
                        new
                        {
                            PermissionId = 7,
                            Name = "to_update_bid"
                        },
                        new
                        {
                            PermissionId = 8,
                            Name = "to_delete_bid"
                        },
                        new
                        {
                            PermissionId = 9,
                            Name = "to_get_all_bids"
                        },
                        new
                        {
                            PermissionId = 10,
                            Name = "to_get_bid_by_id"
                        },
                        new
                        {
                            PermissionId = 11,
                            Name = "to_create_auction_schedule"
                        },
                        new
                        {
                            PermissionId = 12,
                            Name = "to_update_auction_schedule"
                        },
                        new
                        {
                            PermissionId = 13,
                            Name = "to_delete_auction_schedule"
                        },
                        new
                        {
                            PermissionId = 14,
                            Name = "to_get_all_auction_schedules"
                        },
                        new
                        {
                            PermissionId = 15,
                            Name = "to_get_auction_schedule_by_id"
                        },
                        new
                        {
                            PermissionId = 16,
                            Name = "to_create_lable"
                        },
                        new
                        {
                            PermissionId = 17,
                            Name = "to_update_lable"
                        },
                        new
                        {
                            PermissionId = 18,
                            Name = "to_delete_lable"
                        },
                        new
                        {
                            PermissionId = 19,
                            Name = "to_get_all_lables"
                        },
                        new
                        {
                            PermissionId = 20,
                            Name = "to_get_lable_by_id"
                        },
                        new
                        {
                            PermissionId = 21,
                            Name = "to_create_product"
                        },
                        new
                        {
                            PermissionId = 22,
                            Name = "to_update_product"
                        },
                        new
                        {
                            PermissionId = 23,
                            Name = "to_delete_product"
                        },
                        new
                        {
                            PermissionId = 24,
                            Name = "to_get_all_products"
                        },
                        new
                        {
                            PermissionId = 25,
                            Name = "to_get_product_by_id"
                        },
                        new
                        {
                            PermissionId = 26,
                            Name = "to_create_payment"
                        },
                        new
                        {
                            PermissionId = 27,
                            Name = "to_update_payment"
                        },
                        new
                        {
                            PermissionId = 28,
                            Name = "to_delete_payment"
                        },
                        new
                        {
                            PermissionId = 29,
                            Name = "to_get_all_payments"
                        },
                        new
                        {
                            PermissionId = 30,
                            Name = "to_get_payment_by_id"
                        },
                        new
                        {
                            PermissionId = 31,
                            Name = "to_create_category"
                        },
                        new
                        {
                            PermissionId = 32,
                            Name = "to_update_category"
                        },
                        new
                        {
                            PermissionId = 33,
                            Name = "to_delete_category"
                        },
                        new
                        {
                            PermissionId = 34,
                            Name = "to_get_all_categories"
                        },
                        new
                        {
                            PermissionId = 35,
                            Name = "to_get_category_by_id"
                        },
                        new
                        {
                            PermissionId = 36,
                            Name = "to_create_transaction"
                        },
                        new
                        {
                            PermissionId = 37,
                            Name = "to_update_transaction"
                        },
                        new
                        {
                            PermissionId = 38,
                            Name = "to_delete_transaction"
                        },
                        new
                        {
                            PermissionId = 39,
                            Name = "to_get_all_transactions"
                        },
                        new
                        {
                            PermissionId = 40,
                            Name = "to_get_transaction_by_id"
                        },
                        new
                        {
                            PermissionId = 41,
                            Name = "to_create_user"
                        },
                        new
                        {
                            PermissionId = 42,
                            Name = "to_update_user"
                        },
                        new
                        {
                            PermissionId = 43,
                            Name = "to_delete_user"
                        },
                        new
                        {
                            PermissionId = 44,
                            Name = "to_get_all_users"
                        },
                        new
                        {
                            PermissionId = 45,
                            Name = "to_get_user_by_id"
                        },
                        new
                        {
                            PermissionId = 46,
                            Name = "to_create_report"
                        },
                        new
                        {
                            PermissionId = 47,
                            Name = "to_update_report"
                        },
                        new
                        {
                            PermissionId = 48,
                            Name = "to_delete_report"
                        },
                        new
                        {
                            PermissionId = 49,
                            Name = "to_get_all_reports"
                        },
                        new
                        {
                            PermissionId = 50,
                            Name = "to_get_report_by_id"
                        },
                        new
                        {
                            PermissionId = 51,
                            Name = "to_create_user_role"
                        },
                        new
                        {
                            PermissionId = 52,
                            Name = "to_update_user_role"
                        },
                        new
                        {
                            PermissionId = 53,
                            Name = "to_delete_user_role"
                        },
                        new
                        {
                            PermissionId = 54,
                            Name = "to_get_all_user_roles"
                        },
                        new
                        {
                            PermissionId = 55,
                            Name = "to_get_user_role_by_id"
                        },
                        new
                        {
                            PermissionId = 56,
                            Name = "to_create_permission"
                        },
                        new
                        {
                            PermissionId = 57,
                            Name = "to_update_permission"
                        },
                        new
                        {
                            PermissionId = 58,
                            Name = "to_delete_permission"
                        },
                        new
                        {
                            PermissionId = 59,
                            Name = "to_get_all_permissions"
                        },
                        new
                        {
                            PermissionId = 60,
                            Name = "to_get_permission_by_id"
                        },
                        new
                        {
                            PermissionId = 61,
                            Name = "to_create_user_profile"
                        },
                        new
                        {
                            PermissionId = 62,
                            Name = "to_update_user_profile"
                        },
                        new
                        {
                            PermissionId = 63,
                            Name = "to_delete_user_profile"
                        },
                        new
                        {
                            PermissionId = 64,
                            Name = "to_get_all_user_profiles"
                        },
                        new
                        {
                            PermissionId = 65,
                            Name = "to_get_user_profile_by_id"
                        },
                        new
                        {
                            PermissionId = 66,
                            Name = "to_create_notification"
                        },
                        new
                        {
                            PermissionId = 67,
                            Name = "to_update_notification"
                        },
                        new
                        {
                            PermissionId = 68,
                            Name = "to_delete_notification"
                        },
                        new
                        {
                            PermissionId = 69,
                            Name = "to_get_all_notifications"
                        },
                        new
                        {
                            PermissionId = 70,
                            Name = "to_get_notification_by_id"
                        },
                        new
                        {
                            PermissionId = 71,
                            Name = "to_create_activity_log"
                        },
                        new
                        {
                            PermissionId = 72,
                            Name = "to_update_activity_log"
                        },
                        new
                        {
                            PermissionId = 73,
                            Name = "to_delete_activity_log"
                        },
                        new
                        {
                            PermissionId = 74,
                            Name = "to_get_all_activity_logs"
                        },
                        new
                        {
                            PermissionId = 75,
                            Name = "to_get_activity_log_by_id"
                        },
                        new
                        {
                            PermissionId = 76,
                            Name = "to_create_otp"
                        },
                        new
                        {
                            PermissionId = 77,
                            Name = "to_update_otp"
                        },
                        new
                        {
                            PermissionId = 78,
                            Name = "to_delete_otp"
                        },
                        new
                        {
                            PermissionId = 79,
                            Name = "to_get_all_otps"
                        },
                        new
                        {
                            PermissionId = 80,
                            Name = "to_get_otp_by_id"
                        });
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Shippingfee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.ShippingDetails", b =>
                {
                    b.Property<int>("ShippingDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingDetailsId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BidId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ShippingDetailsId");

                    b.HasIndex("BidId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ShippingDetails");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("TransactionId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@lansuwa.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Admin",
                            IsVerified = true,
                            LastName = "User",
                            Password = "KtmYrvqbhm6PbytrQiY/e/StPH2XqMJNk4KVer4+AaY=",
                            PasswordSalt = "T2NxIwaC6pQOcB5Z6C19rQ==",
                            UserRoleId = 1
                        });
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProfileId"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SellerRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = 1,
                            Role = "admin"
                        },
                        new
                        {
                            UserRoleId = 2,
                            Role = "buyer"
                        });
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.WatchAuction", b =>
                {
                    b.Property<int>("WatchAuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatchAuctionId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<int?>("BidId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WatchAuctionId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchAuctions");
                });

            modelBuilder.Entity("PermissionUserRole", b =>
                {
                    b.Property<int>("PermissionsPermissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserRolesUserRoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionsPermissionId", "UserRolesUserRoleId");

                    b.HasIndex("UserRolesUserRoleId");

                    b.ToTable("UserRolePermissions", (string)null);
                });

            modelBuilder.Entity("AuctionLable", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Auction", null)
                        .WithMany()
                        .HasForeignKey("AuctionsAuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionManagementAPI.Models.Lable", null)
                        .WithMany()
                        .HasForeignKey("LablesLableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.ActivityLog", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Auction", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Product", "Product")
                        .WithMany("Auctions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.AuctionSchedule", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Auction", "Auction")
                        .WithOne("AuctionSchedule")
                        .HasForeignKey("AuctionManagementAPI.Models.AuctionSchedule", "AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Bid", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionManagementAPI.Models.User", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Category", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Notification", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Otp", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.User", "User")
                        .WithMany("Otps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Payment", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Auction", "Auction")
                        .WithOne("Payment")
                        .HasForeignKey("AuctionManagementAPI.Models.Payment", "AuctionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AuctionManagementAPI.Models.Bid", "Bid")
                        .WithOne("Payment")
                        .HasForeignKey("AuctionManagementAPI.Models.Payment", "BidId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuctionManagementAPI.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Product", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Report", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.ShippingDetails", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Bid", "Bid")
                        .WithOne("shippingDetails")
                        .HasForeignKey("AuctionManagementAPI.Models.ShippingDetails", "BidId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuctionManagementAPI.Models.User", "User")
                        .WithMany("ShippingDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Transaction", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.User", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.UserProfile", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("AuctionManagementAPI.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.WatchAuction", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionManagementAPI.Models.Bid", "Bid")
                        .WithMany()
                        .HasForeignKey("BidId");

                    b.HasOne("AuctionManagementAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermissionUserRole", b =>
                {
                    b.HasOne("AuctionManagementAPI.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionManagementAPI.Models.UserRole", null)
                        .WithMany()
                        .HasForeignKey("UserRolesUserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Auction", b =>
                {
                    b.Navigation("AuctionSchedule");

                    b.Navigation("Bids");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Bid", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("shippingDetails");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.Product", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Bids");

                    b.Navigation("Notifications");

                    b.Navigation("Otps");

                    b.Navigation("Payments");

                    b.Navigation("Reports");

                    b.Navigation("ShippingDetails");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("AuctionManagementAPI.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
